// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/hedwigz/ent-tidb/ent/runtime.go

const (
	Version = "v0.10.2-0.20220310154057-2853afc1dc2e"           // Version of ent codegen.
	Sum     = "h1:JsvE0URjgoOMH+V1+qnb4DL/FTZJPkJZbh1xdeG13Xg=" // Sum of ent codegen.
)
