// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/hedwigz/ent-tidb/ent/runtime.go

const (
	Version = "v0.10.2-0.20220313150850-a27f753bc800"           // Version of ent codegen.
	Sum     = "h1:jXrEtAD941EjMvNdEGucvejy3YRRmWKFEFDM/W/9ICs=" // Sum of ent codegen.
)
